import React from 'react';
import { Link } from 'react-router-dom';
import HelpLayout from '../HelpLayout';

const HowScoringWorks: React.FC = () => {
  return (
    <HelpLayout
      title="Output, Scoring &amp; Comparison"
      breadcrumbs={[{ label: 'How Scoring Works' }]}
    >
      {/* ─── SECTION 1: Output Overview ───────────────────────────────── */}
      <div className="not-prose bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-6 mb-8">
        <p className="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-2">Overview</p>
        <p className="text-gray-700 dark:text-gray-300">Understanding and working with the content generated by CopyZap — from output cards to scoring, comparison, and feature interactions.</p>
      </div>

      <div className="not-prose grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div className="bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-lg p-4">
          <p className="text-xs font-semibold uppercase tracking-widest text-emerald-700 dark:text-emerald-400 mb-2">Use this when:</p>
          <ul className="list-disc ml-5 text-sm text-gray-700 dark:text-gray-300 space-y-1">
            <li>You want to evaluate copy quality</li>
            <li>Choosing between multiple versions</li>
            <li>Understanding comparison scores and rankings</li>
          </ul>
        </div>
        <div className="bg-orange-50 dark:bg-orange-900/20 border border-orange-200 dark:border-orange-800 rounded-lg p-4">
          <p className="text-xs font-semibold uppercase tracking-widest text-orange-700 dark:text-orange-400 mb-2">What you'll get:</p>
          <ul className="list-disc ml-5 text-sm text-gray-700 dark:text-gray-300 space-y-1">
            <li>Objective quality scores for your content</li>
            <li>Data-driven comparison of competing versions</li>
            <li>Confidence to pick winning copy</li>
          </ul>
        </div>
      </div>

      <h2>Output Cards</h2>
      <p className="text-gray-700 dark:text-gray-300">After generation, each result appears as an output card. Cards contain:</p>

      <div className="not-prose space-y-4 mb-8">
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Main Copy</h3>
          <p className="text-gray-700 dark:text-gray-300">The primary generated content based on your inputs and requirements.</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Quality Scores</h3>
          <p className="text-gray-700 dark:text-gray-300">AI-powered evaluation of your content's quality, clarity, and effectiveness. Click the Score button on any output card, or pre-enable scoring in Optional Features.</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Headlines</h3>
          <p className="text-gray-700 dark:text-gray-300">Multiple headline variations optimized for engagement (if enabled).</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">SEO Metadata</h3>
          <p className="text-gray-700 dark:text-gray-300">Meta titles, descriptions, URL slugs, and other SEO elements (if enabled).</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
          <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Alternative Versions</h3>
          <p className="text-gray-700 dark:text-gray-300">Additional copy variations created with different approaches.</p>
        </div>
      </div>

      <h3>Actions Available on Output Cards</h3>
      <ul>
        <li><strong>Copy:</strong> Copy any section to your clipboard with one click</li>
        <li><strong>Export:</strong> Download as HTML or copy as Markdown</li>
        <li><strong>Save:</strong> Save to your dashboard for future reference</li>
        <li><strong>Generate Alternatives:</strong> Create new variations</li>
        <li><strong>Apply Voice Style:</strong> Transform content with different communication styles</li>
        <li><strong>Score:</strong> Get quality evaluation and improvement suggestions</li>
        <li><strong>Compare:</strong> Compare multiple versions side-by-side</li>
      </ul>

      <div className="not-prose bg-yellow-50 dark:bg-yellow-900/20 rounded-lg p-3 border border-yellow-200 dark:border-yellow-800 mb-8 mt-4">
        <p className="text-sm text-gray-700 dark:text-gray-300">
          <strong>Pro Tip:</strong> Always review and refine generated content before using it. The AI provides a strong starting point, but your expertise and judgment are essential for final quality.
        </p>
      </div>

      {/* ─── SECTION 2: Scoring Explained ─────────────────────────────── */}
      <hr className="my-8" />
      <h2>Content Scoring</h2>
      <p className="text-gray-700 dark:text-gray-300">Get AI-powered quality scores for your content. The primary way to score is to click the <strong>Score</strong> button on any output card after generation. You can also pre-enable scoring in Optional Features, which automatically scores each output at generation time.</p>

      <div className="not-prose grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Clarity Score</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">How easy your content is to understand</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Persuasiveness</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">How effectively it motivates action</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Engagement</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">How well it captures and maintains attention</p>
        </div>

        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 border border-gray-200 dark:border-gray-700">
          <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Overall Quality</h3>
          <p className="text-sm text-gray-600 dark:text-gray-400">Comprehensive evaluation of all factors (0–100)</p>
        </div>
      </div>

      {/* ─── SECTION 3: Compare Feature ───────────────────────────────── */}
      <hr className="my-8" />
      <h2>Compare &amp; Blend</h2>
      <p className="text-gray-700 dark:text-gray-300">Compare different copy versions and blend the best elements into one optimized result.</p>

      <h3>How to Use Compare</h3>
      <div className="not-prose bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700 mb-6">
        <ol className="list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
          <li>Generate multiple copy versions (main + alternatives)</li>
          <li>Click the <strong>"Compare All Outputs"</strong> button in the results bar</li>
          <li>AI analyzes all versions and shows:
            <ul className="list-disc ml-6 mt-2">
              <li>Each version scored on Conversion, Trust, and Risk</li>
              <li>A ranked winner with written analysis</li>
              <li>Strengths and weaknesses of each version</li>
            </ul>
          </li>
          <li>Pick your version — the comparison is a snapshot, your original cards remain</li>
        </ol>
      </div>

      <p><strong>What to look for when comparing:</strong></p>
      <ul>
        <li>Which version has the strongest opening?</li>
        <li>Which call-to-action is most compelling?</li>
        <li>Which version better addresses pain points?</li>
        <li>Which has better flow and readability?</li>
        <li>Which version aligns best with your brand voice?</li>
      </ul>

      <h3>How Blending Works</h3>
      <div className="not-prose bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700 mb-6">
        <ol className="list-decimal list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
          <li>Select 2-3 copy versions to blend</li>
          <li>The AI analyzes strengths of each version</li>
          <li>Elements are intelligently combined</li>
          <li>A new blended version is generated</li>
          <li>The blend maintains coherent flow and voice</li>
        </ol>
      </div>

      <h3>Comparison Persistence</h3>
      <div className="not-prose bg-blue-50 dark:bg-blue-900/20 rounded-lg p-6 border border-blue-200 dark:border-blue-800 mb-6">
        <p className="text-gray-700 dark:text-gray-300 mb-4">
          <strong>Important:</strong> Comparison results are static snapshots. Once created, a comparison card does not update automatically when you add new outputs.
        </p>
        <div className="p-4 bg-white dark:bg-gray-900 rounded border border-blue-300 dark:border-blue-700">
          <p className="text-sm font-semibold text-gray-900 dark:text-white mb-2">Example:</p>
          <ol className="list-decimal list-inside space-y-1 text-sm text-gray-700 dark:text-gray-300 ml-4">
            <li>Generate 3 alternatives → Click "Compare All Outputs" → Get Comparison Card A</li>
            <li>Apply voice style to best alternative → Comparison Card A remains unchanged</li>
            <li>Click "Compare All Outputs" again → Get Comparison Card B (now includes all outputs)</li>
            <li>Both comparisons are saved for reference</li>
          </ol>
        </div>
      </div>

      {/* ─── SECTION 4: Feature Interactions ─────────────────────────── */}
      <hr className="my-8" />
      <h2>Feature Interactions</h2>
      <p className="text-gray-700 dark:text-gray-300">Understand how CopyZap's features work together to create powerful copywriting workflows.</p>

      <h3>Voice Systems Integration</h3>
      <p className="text-gray-700 dark:text-gray-300">Brand Voice and Voice Styles work together to shape your content.</p>
      <ul>
        <li><strong>Brand Voice</strong> sets the baseline style applied during generation</li>
        <li><strong>Voice Styles</strong> are applied post-generation as transformations</li>
        <li>Specific Tone or Special Instructions in the form override Brand Voice for that session</li>
      </ul>

      <h3>Templates + Brand Voice</h3>
      <p className="text-gray-700 dark:text-gray-300">Templates can include brand voice associations for consistent content. When you load a template, the associated brand voice is automatically selected.</p>

      <div className="not-prose bg-green-50 dark:bg-green-900/20 rounded-lg p-6 border border-green-200 dark:border-green-800 mb-8">
        <p className="font-semibold text-gray-900 dark:text-white mb-2">Best Practices</p>
        <ul className="list-disc ml-6 text-green-900 dark:text-green-100 space-y-1">
          <li>Generate at least 2-3 versions before comparing</li>
          <li>Use different voice styles for more variety</li>
          <li>Compare scores as well as content</li>
          <li>Blend versions with complementary strengths</li>
          <li>Always review blended content for coherence</li>
          <li>Click "Compare All Outputs" again after creating new variations to include them in analysis</li>
        </ul>
      </div>

      <div className="not-prose bg-gradient-to-r from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-800/20 border border-blue-200 dark:border-blue-700 rounded-lg p-6 mb-8">
        <p className="text-sm font-semibold text-blue-900 dark:text-blue-100 mb-3">Try this now:</p>
        <div className="space-y-2">
          <Link to="/" className="block text-sm font-medium text-blue-600 dark:text-blue-400 hover:underline">Go to Copy Maker →</Link>
          <p className="text-xs text-gray-600 dark:text-gray-400">Generate 2 versions, then click "Compare All Outputs"</p>
        </div>
      </div>

      <h2>Related Topics</h2>
      <ul>
        <li><Link to="/help/optional-features" className="text-blue-600 dark:text-blue-400 hover:underline">Optional Features</Link> — enable scoring, SEO, GEO, and headlines</li>
        <li><Link to="/help/voice-styles-and-blending" className="text-blue-600 dark:text-blue-400 hover:underline">Voice Styles &amp; Blending</Link> — personas and style transformations</li>
        <li><Link to="/help/core-workflows" className="text-blue-600 dark:text-blue-400 hover:underline">Core Workflows</Link> — see full compare &amp; blend workflow</li>
      </ul>

      <hr className="my-8" />
      <p className="text-sm text-gray-600 dark:text-gray-400">Last updated: 2026-04-17</p>
    </HelpLayout>
  );
};

export default HowScoringWorks;
