import React from 'react';
import HelpLayout from '../HelpLayout';

const OutputFeatures: React.FC = () => {
  return (
    <HelpLayout
      title="Generated Output"
      breadcrumbs={[{ label: 'Generated Output' }]}
    >
      <div className="space-y-6">
        <p className="text-lg text-gray-700 dark:text-gray-300">
          Understanding and working with the content generated by CopyZap.
        </p>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">Output Components</h2>
          <p className="text-gray-700 dark:text-gray-300">
            After generation, you'll see several components:
          </p>

          <div className="space-y-4">
            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Main Copy</h3>
              <p className="text-gray-700 dark:text-gray-300">
                The primary generated content based on your inputs and requirements.
              </p>
            </div>

            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Quality Scores</h3>
              <p className="text-gray-700 dark:text-gray-300">
                AI-powered evaluation of your content's quality, clarity, and effectiveness (if enabled).
              </p>
            </div>

            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Headlines</h3>
              <p className="text-gray-700 dark:text-gray-300">
                Multiple headline variations optimized for engagement (if enabled).
              </p>
            </div>

            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">SEO Metadata</h3>
              <p className="text-gray-700 dark:text-gray-300">
                Meta titles, descriptions, URL slugs, and other SEO elements (if enabled).
              </p>
            </div>

            <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-6 border border-gray-200 dark:border-gray-700">
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">Alternative Versions</h3>
              <p className="text-gray-700 dark:text-gray-300">
                Additional copy variations created with different approaches.
              </p>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">Working with Output</h2>
          <p className="text-gray-700 dark:text-gray-300">
            You can perform several actions on generated content:
          </p>

          <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
            <li><strong>Copy:</strong> Copy any section to your clipboard with one click</li>
            <li><strong>Edit:</strong> Make inline edits to refine the content</li>
            <li><strong>Export:</strong> Download as HTML or copy as Markdown</li>
            <li><strong>Save:</strong> Save to your dashboard for future reference</li>
            <li><strong>Generate Alternatives:</strong> Create new variations of specific sections</li>
            <li><strong>Apply Voice Style:</strong> Transform content with different communication styles</li>
            <li><strong>Score:</strong> Get quality evaluation and improvement suggestions</li>
            <li><strong>Compare:</strong> Compare multiple versions side-by-side</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">On-Demand Generation</h2>
          <p className="text-gray-700 dark:text-gray-300">
            Generate additional content elements on-demand:
          </p>
          <ul className="list-disc list-inside space-y-2 text-gray-700 dark:text-gray-300 ml-4">
            <li>More headline variations</li>
            <li>Alternative copy versions</li>
            <li>Content refinements</li>
            <li>Voice style variations</li>
            <li>SEO metadata variations</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900 dark:text-white">Export Options</h2>
          <p className="text-gray-700 dark:text-gray-300">
            CopyZap offers two export formats designed to cover all your needs:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 border border-blue-200 dark:border-blue-800">
              <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Copy as Markdown</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">Instant clipboard copy with formatted Markdown</p>
              <p className="text-xs text-gray-500 dark:text-gray-500">Perfect for Notion, Slack, GitHub, and documentation</p>
            </div>

            <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-4 border border-green-200 dark:border-green-800">
              <h3 className="font-semibold text-gray-900 dark:text-white mb-2">Export as HTML</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">Styled HTML file for professional presentation</p>
              <p className="text-xs text-gray-500 dark:text-gray-500">Print to PDF from browser for client deliverables</p>
            </div>
          </div>

          <div className="bg-yellow-50 dark:bg-yellow-900/20 rounded-lg p-3 border border-yellow-200 dark:border-yellow-800 mt-4">
            <p className="text-sm text-gray-700 dark:text-gray-300">
              <strong>Need a PDF?</strong> Export as HTML, open in your browser, and use File → Print → Save as PDF. This gives you full control over PDF formatting.
            </p>
          </div>
        </section>

        <div className="mt-8 p-6 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
          <h3 className="text-xl font-semibold text-blue-900 dark:text-blue-100 mb-3">Pro Tip</h3>
          <p className="text-blue-800 dark:text-blue-200">
            Always review and refine generated content before using it. The AI provides a strong starting point, but your expertise and judgment are essential for final quality.
          </p>
        </div>
      </div>
    </HelpLayout>
  );
};

export default OutputFeatures;
